name: Run Newman Tests

on: [push]

jobs:
  newman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Collection 1
        run: newman run collections/TESTING.postman_collection.json -e TEST.postman_environment.json

      - name: Run Collection 2
        run: newman run collections/TESTING_1.postman_collection.json -e TEST.postman_environment.json
